project:
  type: book

book:
  title: "Algorithms & Data Structures Solutions - SoSe 24"
  author: "Igor Dimitrov"
  date: "4/22/2024"
  chapters:
    - index.qmd
    - 01/01.qmd

  downloads: pdf

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



