project:
  type: book

book:
  title: "Algorithms & Data Structures Solutions - SoSe 24"
  author: "Igor Dimitrov"
  date: "4/22/2024"
  chapters:
    - index.qmd
    - 01/01.qmd
    - 02/02.qmd
    - 03/03.qmd

  downloads: pdf
number-depth: 1 

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    include-in-header: 
      - text : |
          \usepackage{fvextra}
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}



