test_list: test_list.cc list.hpp
	g++ --std=c++17 -Wall -Wextra -Wpedantic -Werror -g -O0 -o test_list test_list.cc
unique_impl: unique_impl.cc
	g++ --std=c++17 -Wall -Wextra -Wpedantic -Werror -g -O0 -o unique_impl unique_impl.cc
unique_test: unique_test.cc
	g++ --std=c++17 -Wall -Wextra -Wpedantic -Werror -g -O0 -o unique_test unique_test.cc